//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestGraphQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journal()
        {
            this.Manuscripts = new HashSet<Manuscript>();
        }
    
        public string Journal1 { get; set; }
        public Nullable<bool> IsPMC { get; set; }
        public string JournalTypeID { get; set; }
        public Nullable<bool> IsSold { get; set; }
        public Nullable<short> JournalPriority { get; set; }
        public string JournalSubCode { get; set; }
        public Nullable<int> Journals_JournalOwner { get; set; }
        public string JournalFullName { get; set; }
        public string GalleyproofDirection { get; set; }
        public Nullable<bool> ActiveIntegrationTool { get; set; }
        public Nullable<int> ProductionEditor { get; set; }
        public int VendorId { get; set; }
        public Nullable<int> JournalOwnerId { get; set; }
        public string Issn { get; set; }
        public string EIssn { get; set; }
        public Nullable<int> RevisionRatio { get; set; }
        public int MethodId { get; set; }
        public int ManuscriptCounter { get; set; }
    
        public   User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public   ICollection<Manuscript> Manuscripts { get; set; }
    }
}
