//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestGraphQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manuscript
    {
        public int ManuscriptId { get; set; }
        public string JournalSubCode { get; set; }
        public int VendorId { get; set; }
        public bool Closed { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public bool Paused { get; set; }
        public bool Withdrawn { get; set; }
        public Nullable<int> MsPages { get; set; }
        public bool AuthorConfirmed { get; set; }
        public bool OriginalFilesDownloaded { get; set; }
        public string CMSURL { get; set; }
        public Nullable<int> Fig_relabel { get; set; }
        public Nullable<int> Fig_redraw { get; set; }
        public Nullable<int> Clipart { get; set; }
        public Nullable<int> PixelByPixel { get; set; }
        public Nullable<int> ref_count { get; set; }
        public Nullable<int> Tables_Num { get; set; }
        public Nullable<int> Other_Annexes { get; set; }
        public Nullable<bool> StopIndexing { get; set; }
        public Nullable<System.DateTime> StopIndexingDate { get; set; }
        public Nullable<bool> UnderCorrection { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> InsertionDate { get; set; }
        public Nullable<int> UpdateVolumeCheckStatus { get; set; }
        public Nullable<int> InlineEquation { get; set; }
        public Nullable<int> DisplayedEquation { get; set; }
        public Nullable<int> changeProofStatus { get; set; }
    
        public   Journal Journal { get; set; }
        public   User User { get; set; }
    }
}
